### ISSUE TITLE
Enabling/ Disabling Cluster Service

### ISSUE THREAD

**Issue by emyatsuna** [dsccommunity/xFailOverCluster#206]
Hi, I was checking the resources for `xFailOverCluster`. I wonder if there's an `autostart`/ `restart`/ `stop`/` start` functions of the auto-generated cluster? Have I missed out a resource in this repository? Please advise. Thanks a lot.

**Comment by johlju** [comment]
What are the scenario you are trying to solve? For example using `restart` does not sound like an enforceable desired state. Is it a property you want to change?

**Comment by emyatsuna** [comment]
Hi, I would like the new cluster to restart itself after configurations within it so that it will reconnect to AD and acquire additional priviledges as needed.

**Comment by johlju** [comment]
What have you configured in the cluster that needs the entire cluster to be restarted? It is probably that resource that make such configuration that should handle the restart of the cluster. 🤔
