### ISSUE TITLE
404 error on xClusterQuorum node and cloud documentation

### ISSUE THREAD

**Issue by JulianFavell** [dsccommunity/xFailOverCluster#208]
Hi All, 

I have recently been trying to go create SQL high availability using DSC, im currently stuck on using this powershell module to assign a Cluster Quorum to a cluster and have it register a cloud witness. When i try to acces the example link for cloud it gives me a 404 error. I have tried it on multiple browsers with the same experience. Please make this link accessible again.

https://github.com/PowerShell/xFailOverCluster/blob/dev/Examples/Resources/xClusterQuorum/5-SetQuorumToNodeAndCloudMajority.1

Thanks, 

Julian

**Comment by johlju** [comment]
The correct link should have .ps1 at the end. I seems the link is missing that in the README.md, see this line https://github.com/PowerShell/xFailOverCluster/blame/dev/README.md#L269

The correct link:
https://github.com/PowerShell/xFailOverCluster/blob/dev/Examples/Resources/xClusterQuorum/5-SetQuorumToNodeAndCloudMajority.ps1
