### ISSUE TITLE
xCluster: DomainAdministratorCredential should not be mandatory

### ISSUE THREAD

**Issue by johlju** [dsccommunity/xFailOverCluster#70]
**Details of the scenario you tried and the problem that is occurring:**
It should be possible to use built-in parameter `PsDscRunAsCredential` for WMF 5.x, so the parameter `DomainAdministratorCredential` should not be mandatory. 

**The DSC configuration that is using the resource (as detailed as possible):**
```powershell
xCluster "Create$($Node.FailoverClusterName)"
{
    Name = $Node.FailoverClusterName
    StaticIPAddress = $Node.FailoverClusterIPAddress

    PsDscRunAsCredential = $SqlInstallCredential
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
n/a

**Comment by emyatsuna** [comment]
Hi, I'm also having the same problem. Is there any updates for this one? Thanks.
I tried to manually create Cluster via GUI in my server and it went smoothly. I am using the same credentials (username&password) as input for the mandatory `DomainAdministratorCredential` but upon execution, I get the error below.

`Error: PowerShell DSC resource MSFT_xCluster  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Can't logon as user <username>.`

**Comment by johlju** [comment]
It doesn’t look like the same issue. Please post a new issue and provide the requested information mentioned in the issue template.
